.TH MOLN 1
.SH NAME
moln \- Convenience shell script to work with cloud services.

.SH SYNOPSIS
.B moln [cloud] [command] {options}

.SH DESCRIPTION

Moln present a uniform api that is implemented using cli commands from different
cloud providers. This can be used to work on multiple cloud providers (aws,gcloud,azure)
using the same commands. Moln can also print the underlying cli command to refresh
your memory or when you need to do more advanced commands against the cloud provider.

Feel free to copy snippets and learn from this code. But as a whole it
is licensed under the MIT license and requires legal notices.

.SH EXAMPLES

.B moln aws install
.B moln gcloud install
.B moln azure install

Download the aws cli commands and put a link to them inside your $HOME/bin directory and put the actual code in $HOME/opt.

.B moln aws whoami

Show your cloud identity/account information.

.B moln aws list-vpcs

Show a list of virtual private clouds.

.B moln all list-vms

Show a list of virtual machines for all your cloud providers for your accounts.

.B moln aws assume-role full_access_dns TimeForWork

Create a subshell, within which you have access to a different role to gain privileges. The subshell session is called TimeForWork.

.SH OPTIONS
\fB\-l\fR \fB\--list-commands\fR list all available commands.
.br
\fB\-lc\fR \fB\--list-clouds\fR list all available clouds.
.br
\fB\-v\fR verbose will show the underlying cli commands.
.br
\fB\-d\fR debug with a lot of information.
.br

.SH COMMANDS
· Basic_Information

\fBwhoami\fR
.br
Display active account/identity.

· Buckets

\fBlist-buckets\fR
.br
List storage buckets, ie aws s3/gcloud storage/azure blobs.

· Cloud_Console


· Costs


· Dns


· Groups


· Install_Tools


· Public_IPs


· Policies


· Roles


· Subnets_inside_a_VPC


· Users


· Vms

\fBlist-vms\fR
.br
List all available virtual machines.

· Virtual_Private_Clouds

\fBlist-vpcs\fR
.br
List virtual private clouds/networks, aka vpc:s and vnets.

· WebApis



.SH AUTHOR
Written by Fredrik Öhrström.

.SH COPYRIGHT
Copyright \(co 2022 Fredrik Öhrström.
.br
License MIT
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
