name: Build Ubuntu
on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+_beta'
      - '[0-9]+.[0-9]+.[0-9]+_candidate'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: MAKE
      run: make
    - id: TEST
      run: make test
