name: Build Ubuntu
on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+_beta'
      - '[0-9]+.[0-9]+.[0-9]+_candidate'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: CHECKOUT_SOURCE
    - uses: actions/checkout@v3
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: sudo apt install -y eatmydata libtidy-dev libxml2-dev libxslt1-dev unzip jq
    - id: CONFIGURE
      run: eatmydata ./configure
    - id: MAKE
      run: eatmydata make
    - id: TEST
      run: eatmydata make test
