name: Self Hosted Ubuntu
on:
  push:

jobs:
  build:
    if: github.repository == 'viklauverk/moln.private'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - id: GO
      run: /work/runner/test_moln.sh