name: Additional Testing
on:
  push:

jobs:
  build:
    if: endsWith(github.repository, '.private')
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - id: GO
      run: /work/tools/test.sh